name: Main

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v1
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          yarn
          node index.js > fake-italian-data.csv
      - name: Test
        run: cat Release.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: fake-italian-data.csv
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
